# El servidor escucha en el puerto 1194 de UDP.
port 1194
proto udp

dev tun

# Especificamos la ubicación de las claves.
ca /home/vpnserver/ca/ca.pem
cert /home/vpnserver/server/server.pem
key /home/vpnserver/server/server.key
dh /home/vpnserver/server/dh.pem

# Establecemos las direcciones de la VPN (10.8.0/24).
server 10.8.0.0 255.255.255.0

keepalive 10 120

persist-key
persist-tun

verb 4
